### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by UndisclosedBox83** [blandman/homebridge-carwings#11]
Hello and thank you for the plugin. Seems very useful.
I installed the plugin successfully, but when I run homebridge, I get the following:

[2018-1-5 13:01:52] [LEAF] Carwings requestUpdate failed to get status
 session is not a function
TypeError: Cannot read property '0' of undefined
    at getsessionid (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1343:39)
    at /opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1432:23
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1383:54)
    at step (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1218:23)
    at Object.next (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1199:53)
    at fulfilled (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1190:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property '0' of undefined
    at getsessionid (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1343:39)
    at /opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1432:23
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1383:54)
    at step (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1218:23)
    at Object.next (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1199:53)
    at fulfilled (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1190:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

[2018-1-5 13:13:21] [LEAF] Carwings getHVAC failed to get status
 session is not a function
TypeError: Cannot read property '0' of undefined
    at getsessionid (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1343:39)
    at /opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1432:23
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1383:54)
    at step (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1218:23)
    at Object.next (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1199:53)
    at fulfilled (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1190:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property '0' of undefined
    at getsessionid (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1343:39)
    at /opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1432:23
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1383:54)
    at step (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1218:23)
    at Object.next (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1199:53)
    at fulfilled (/opt/node/lib/node_modules/homebridge-carwings-platform/dist/index.js:1190:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by seanxushen** [comment]
Same problem here. I thought it is specific to me because I am in Canada. Remove the plugin until who can help to fix this.
