### ISSUE TITLE
Issue when running forked Homebridge-carwings platform

### ISSUE THREAD

**Issue by ciaronfitz** [blandman/homebridge-carwings#13]
Hi!
I’m extremely new to this, and may have posted this in the wrong place, I’m hoping someone might be able to advise. I’ve installed the fork plugin from this and get this message when I try to run Homebridge:
Error
    at /opt/nodejs/lib/node_modules/homebridge-carwings-platform/dist/index.js:1321:35
    at step (/opt/nodejs/lib/node_modules/homebridge-carwings-platform/dist/index.js:1218:23)
    at Object.next (/opt/nodejs/lib/node_modules/homebridge-carwings-platform/dist/index.js:1199:53)
    at fulfilled (/opt/nodejs/lib/node_modules/homebridge-carwings-platform/dist/index.js:1190:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
[2018-2-4 20:22:07] [Leaf] Carwings requestUpdate failed to get status
 session is not a function

Thanks in advance!

**Comment by mishakim** [comment]
I assume you're talking about bhagyas's fork - I just installed it, and have the same problem
