### ISSUE TITLE
TypeError: Service.Fanv2 is not a constructor

### ISSUE THREAD

**Issue by ero589** [blandman/homebridge-carwings#3]
Not sure what the issue is but I'm not able to initiate carwings on my homebridge.  

Any advice would be appreciated thanks

`[Leaf] Initializing Carwings accessory...
/usr/local/lib/node_modules/homebridge-carwings/homebridge-carwings.js:45
    this.hvac = new Service.Fanv2(this.name);
                ^

TypeError: Service.Fanv2 is not a constructor
    at new CarwingsAccessory (/usr/local/lib/node_modules/homebridge-carwings/homebridge-carwings.js:45:17)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:262:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
`

**Comment by AshMartian** [comment]
Hello,

Can you confirm your version of Homebridge?

If it is older, try running `npm update homebridge`

**Comment by ero589** [comment]
Thanks for the feedback. I updated Homebridge and I was still having issues, so I uninstalled and re-installed everything (Homebridge and all plug-ins) and that fixed it. Now I'm able to get carwings plugin running. Haven't tested it much but it seems to be working. Will report other bugs if needed.
