### ISSUE TITLE
Cannot read property 'RemoteACOperation'

### ISSUE THREAD

**Issue by ggshepherd** [blandman/homebridge-carwings#4]
Receiving the following error in log output:

🍃 api RemoteACRecordsRequest 👍
{ status: 200 }
TypeError: Cannot read property 'RemoteACOperation' of undefined
    at /usr/lib/node_modules/homebridge-carwings/homebridge-carwings.js:115:42
    at process._tickCallback (internal/process/next_tick.js:109:7)

Car is a 2016 LEAF SV with NissanConnect working via Nissan EV iOS app, third party iOS app "EVA", and Nissan Connect web interface. Tried with and without region in configuration: same result.

Configuration:
accessory: 'Carwings',
     name: 'Leaf',
     email: 'redacted',
     password: 'redacted',
     region: 'NNA',
     updateInterval: 'never'

**Comment by AshMartian** [comment]
My homebridge was down for a while, just got the system back up and get this error too. Will address soon.
